services:
  postgresdb:
    container_name: PostgresDocker
    image: postgres:latest
    ports: 
      - "5435:5432"
    environment:
      POSTGRES_DB: postgres
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: password
    volumes: 
      - postgres_data:/var/lib/postgresql/data
    restart: always

  web:
    container_name: Web
    build:
      context: .
      dockerfile: Web/Dockerfile
    ports:
      - "8085:8085" 
      - "8086:8086"
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
    depends_on:
      - postgresdb
    restart: always

  redis:
     image: redis:latest
     container_name: redis
     ports:
      - "6379:6379"
     restart: always

volumes:
  postgres_data:
